### ISSUE TITLE
Sharing iP code quality feedback [for @lhy-hoyin]

### ISSUE THREAD

**Issue by soc-se-script** [lhy-hoyin/ip#3]
@lhy-hoyin We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/Duke.java` lines `56-58`](https://github.com/lhy-hoyin/ip/blob/cf2250a55bde322fab15ae86994883d14141047f/src/main/java/duke/Duke.java#L56..L58):

```java

    /**
     * Display the number of task in taskList to user.
     */

```

Example from [`src/main/java/duke/Duke.java` lines `101-103`](https://github.com/lhy-hoyin/ip/blob/cf2250a55bde322fab15ae86994883d14141047f/src/main/java/duke/Duke.java#L101..L103):

```java

    /**
     * Start Duke program as a Command Line Interface.
     */

```

Example from [`src/main/java/duke/command/Command.java` lines `32-39`](https://github.com/lhy-hoyin/ip/blob/cf2250a55bde322fab15ae86994883d14141047f/src/main/java/duke/command/Command.java#L32..L39):

```java

    /**
     * Parse a String (provided by user) into the correct Command.
     *
     * @param userInput String containing the whole input provided by the user.
     * @return A new instance of the correct Command.
     *         A null of parser is unable to match userInput to the correct Command.
     * @throws DukeException Depending on implementation of the command.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

possible problems in commit [`f97ab1c`](https://github.com/lhy-hoyin/ip/commit/f97ab1c7b7865b4fb3e61bb45d5bf0bcc1d004e4):

`Added java docs, enforced checkstyle`

* Not in imperative mood (?)
             

**Suggestion:** Follow the given [conventions for Git commit messages](https://se-education.org/guides/conventions/git.html) for _future_ commits (no need to modify past commit messages).

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by lhy-hoyin** [comment]
Issues relating to **Aspect: Header Comments** are resolved in commit [`13fa58a`](https://github.com/lhy-hoyin/ip/commit/13fa58a6bff11697a5aa29413e38f83d077f0edb).

Issues relating to **Aspect: Recent Git Commit Message (Subject Only)** are not changed, but will be noted for future commits.
